version: '3.8'

services:
  # api-gateway:
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #   image: api-gateway
  #   container_name: api-gateway
  #   restart: unless-stopped
  #   ports: 
  #     - "8081:8081"
  #   # links:
  #   #   - rabbitmq
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/home/node/app
  #     - ./api-gateway/node_modules:/home/node/app/node_modules
      
  # ads:
  #   build:
  #     context: ./ads
  #     dockerfile: Dockerfile
  #   image: ads
  #   container_name: ads
  #   restart: unless-stopped
  #   ports: 
  #     - "8083:8083"
  #   # links:
  #   #   - rabbitmq
  #   depends_on:
  #     - rabbitmq
  #     - database-mongo
  #   volumes:
  #     - .:/home/node/app
  #     - ./ads/node_modules:/home/node/app/node_modules

  # page-social:
  #   build:
  #     context: ./page-social
  #     dockerfile: Dockerfile
  #   image: page-social
  #   container_name: page-social
  #   restart: unless-stopped
  #   ports: 
  #     - "8084:8084"
  #   # links:
  #   #   - rabbitmq
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/home/node/app
  #     - ./page-social/node_modules:/home/node/app/node_modules
     
  # batch-job:
  #   build:
  #     context: ./batch-job
  #     dockerfile: Dockerfile
  #   image: batch-job
  #   container_name: batch-job
  #   restart: unless-stopped
  #   ports: 
  #     - "8085:8085"
  #   # links:
  #   #   - rabbitmq
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/home/node/app
  #     - ./batch-job/node_modules:/home/node/app/node_modules

  # facebook-api:
  #   build:
  #     context: ./facebook-api
  #     dockerfile: Dockerfile
  #   image: facebook-api
  #   container_name: facebook-api
  #   restart: unless-stopped
  #   ports: 
  #     - "8086:8086"
  #   # links:
  #   #   - rabbitmq
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/home/node/app
  #     - ./facebook-api/node_modules:/home/node/app/node_modules
       
  
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"

      
  database-mongo:
    image: mongo
    ports: 
      - "27017:27017"


# volumes:
#   dbdata:
#   node_modules:  